#PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados
spec:
  capacity:
    storage: mysql-dados
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /meubanco/

---

#PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual