apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app:  php
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  80

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app:  mysql
  clusterIP: None
  ports:
  - port: 3306